---
title: LifeNote 2.0
tagline: Enregister la vie
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: leonnon968@gmail.com
description: This is the website for displaying blog for LifeNote.
baseurl: "/LifeNote"
url: ''
github_username: leonnon968
plugins:
- jekyll-feed
- jekyll-remote-theme
remote_theme: sziv2p/jekyll-theme-scaffold
